with TRIPS AS (

SELECT 

RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATION_ID,
END_STATION_ID,
MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS


FROM {{ source('demo', 'bike') }}
where RIDE_ID != 'ride_id'



)

SELECT

*

FROM TRIPS