WITH CTE AS (
SELECT 

TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

CASE 
WHEN dayname(TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,


MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH,

CASE WHEN MONTH IN (12,1,2)
     THEN 'WINTER'
     WHEN MONTH IN (3,4,5)
     THEN 'SPRING'
     WHEN MONTH IN (6,7,8)
     THEN 'SUMMER'
     ELSE 'AUTUMN'
     END AS STATION_OF_THE_YEAR

FROM 
{{ source('demo', 'bike') }}
where STARTED_AT != 'started_at'


)

select 
*
from CTE
